CREATE TABLE SMS_USER (
    USERNAME VARCHAR2(50) PRIMARY KEY,
    PASSWORD VARCHAR2(100) NOT NULL,
    ROLE     VARCHAR2(20) NOT NULL
);

CREATE TABLE STUDENT (
    ROLL_NO    VARCHAR2(10) PRIMARY KEY,
    FIRST_NAME VARCHAR2(50)  NOT NULL,
    LAST_NAME  VARCHAR2(50)  NOT NULL,
    GENDER     VARCHAR2(10)  NOT NULL,
    EMAIL      VARCHAR2(100),
    PHONE      VARCHAR2(15),
    BRANCH     VARCHAR2(50)  NOT NULL,
    YEAR       NUMBER(1)     NOT NULL,
    SECTION    VARCHAR2(5)   NOT NULL
);

INSERT INTO SMS_USER (USERNAME, PASSWORD, ROLE)
VALUES ('admin', 'admin123', 'ADMIN');
